version: '3.8'

services:

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1


  celery:
    container_name: celery1
    build:
      context: ./app
    command: celery --app=app worker -B -l INFO -Q tasks
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - redis
      - django
      - rabbitmq
