# Generated by Django 4.2.21 on 2025-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
