# Generated by Django 4.2.21 on 2025-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
