# Generated by Django 4.2.21 on 2025-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_defaultgoalgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
