# Generated by Django 4.2.21 on 2025-05-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.taskgroup'),
            preserve_default=False,
        ),
    ]
