# Generated by Django 4.2.21 on 2025-06-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_goal_current_value_goal_priority_goal_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_date', models.DateField(auto_now_add=True)),
                ('current_value', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.goal')),
            ],
        ),
    ]
