# Generated by Django 4.2.21 on 2025-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goal_is_recurring_goal_recurrence_end_goalinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='next_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
    ]
