# Generated by Django 4.2.21 on 2025-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_goal_user_userreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreminder',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
