# Generated by Django 4.2.21 on 2025-06-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_goalinstance_instance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalinstance',
            name='instance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
