# Generated by Django 4.2.21 on 2025-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userreminder_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreminder',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
